# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=3.50
group=com.leobeliik.extremesoundmuffler
java_version=21

# Common
minecraft_version=1.21.6
mod_name=Extreme Sound Muffler
mod_author=LeoBeliik
mod_id=extremesoundmuffler
license=GNU LESSER GENERAL PUBLIC LICENSE
credits=
description=This mod allows you to muffle (almost) any sound selectively,\n\
allowing you to choose the volume of the sound you want between mute and 90%.\n\
This mod also works Clientside only.

minecraft_version_range=[1.21.6,)
parchment_minecraft=1.21.5
parchment_version=2025.06.15

# Fabric
fabric_loader_version=0.16.14
fabric_loom_version=1.10-SNAPSHOT
fabric_version=0.127.0+1.21.6
fiber_version=0.+

# NeoForge
neoforge_version=21.0.6-beta
neoforge_loader_version_range=[4,)
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.6-20250617.151856
# https://projects.neoforged.net/neoforged/moddevgradle
neo_moddev_version=2.0.95

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=true