# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=4.0-ALPHA
group=com.leobeliik.extremesoundmuffler
java_version=21

# Common
minecraft_version=1.21.11
minecraft_version_range=[1.21.11,)
mod_name=Extreme Sound Muffler
mod_author=LeoBeliik
mod_id=extremesoundmuffler
license=GNU LESSER GENERAL PUBLIC LICENSE
credits=
description=This mod allows you to muffle (almost) any sound selectively,\n\
allowing you to choose the volume of the sound you want between mute and 90%.\n\
This mod also works Clientside only.

# https://parchmentmc.org/docs/getting-started
parchment_minecraft=1.21.10
parchment_version=2025.10.12

# Fabric
# https://fabricmc.net/develop/
fabric_loader_version=0.18.2
fabric_loom_version=1.14-SNAPSHOT
fabric_version=0.139.4+1.21.11
fiber_version=0.+

# NeoForge
# https://neoforged.net/
neoforge_version=21.11.45
neoforge_loader_version_range=[4,)
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.11-20251209.172050
# https://projects.neoforged.net/neoforged/moddevgradle
neo_moddev_version=2.0.123

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=true