# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=3.49
group=com.leobeliik.extremesoundmuffler
java_version=21

# Common
minecraft_version=1.21.5
mod_name=Extreme Sound Muffler
mod_author=LeoBeliik
mod_id=extremesoundmuffler
license=GNU LESSER GENERAL PUBLIC LICENSE
credits=
description=This mod allows you to muffle (almost) any sound selectively,\n\
allowing you to choose the volume of the sound you want between mute and 90%.\n\
This mod also works Clientside only.

minecraft_version_range=[1.21.5,)
parchment_minecraft=1.21.4
parchment_version=2025.02.16

# Fabric
fabric_loader_version=0.16.10
fabric_loom_version=1.10-SNAPSHOT
fabric_version=0.119.5+1.21.5
fiber_version=0.23.+

# NeoForge
neoforge_version=21.5.2-beta
neoforge_loader_version_range=[4,)
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.5-20250325.162830
# https://projects.neoforged.net/neoforged/moddevgradle
neo_moddev_version=2.0.80

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
