modLoader = "javafml" #mandatory
loaderVersion = "${neoforge_loader_range}" #mandatory
license = "GNU LESSER GENERAL PUBLIC LICENSE" # Review your options at https://choosealicense.com/.
licenseURL= "https://github.com/LeoBeliik/ExtremeSoundMuffler/blob/master/LICENSE.txt"
issueTrackerURL="https://github.com/LeoBeliik/ExtremeSoundMuffler/issues"
[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${version}" #mandatory
displayName="Extreme Sound Muffler"
logoFile= "esm_logo.png" #optional
authors="LeoBeliik"
description='''
This mod allows you to muffle (almost) any sound selectively,
allowing you to choose the volume of the sound you want between mute and 90%.
This mod also works Clientside only.
'''
[[mixins]]
config = "${mod_id}.mixins.json"
[[mixins]]
config = "${mod_id}.mixins.json"
[[dependencies.${mod_id}]] #optional
modId = "neoforge" #mandatory
mandatory = true #mandatory
versionRange = "${neoforge_loader_range}" #mandatory
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'
[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version_range}]"
ordering = "NONE"
side = "BOTH"