modLoader = "javafml" 
loaderVersion = "${neoforge_loader_version_range}" 
license = "${license}" 
licenseURL = "https://github.com/LeoBeliik/ExtremeSoundMuffler/blob/master/LICENSE.txt"
issueTrackerURL = "https://github.com/LeoBeliik/ExtremeSoundMuffler/issues"
[[mods]] 
    modId = "${mod_id}"
    version = "${version}"
    displayName = "${mod_name}"
    logoFile = "esm_logo.png"
    credits="${credits}"
    authors = "${mod_author}"
    description = '''${description}'''
[[mixins]]
    config = "${mod_id}.mixins.json"
[[dependencies.extremesoundmuffler]]
    modId = "neoforge"
    type="required"
    versionRange = "[${neoforge_version},)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.extremesoundmuffler]]
    modId = "minecraft"
    type="required"
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"






