modLoader = "javafml" #mandatory
loaderVersion = "20.6.62" #mandatory
license = "GNU LESSER GENERAL PUBLIC LICENSE" # Review your options at https://choosealicense.com/.
licenseURL = "https://github.com/LeoBeliik/ExtremeSoundMuffler/blob/master/LICENSE.txt"
issueTrackerURL = "https://github.com/LeoBeliik/ExtremeSoundMuffler/issues"
[[mods]] #mandatory
modId = "extremesoundmuffler" #mandatory
version = "3.45.1" #mandatory
displayName = "Extreme Sound Muffler"
logoFile = "esm_logo.png" #optional
authors = "LeoBeliik"
description = '''
This mod allows you to muffle (almost) any sound selectively,
allowing you to choose the volume of the sound you want between mute and 90%.
This mod also works Clientside only.
'''
[[mixins]]
config = "extremesoundmuffler.mixins.json"
[[dependencies.extremesoundmuffler]] #optional
modId = "neoforge" #mandatory
type = "required" #mandatory
versionRange = "[20.6.60,)" #mandatory
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'
[[dependencies.extremesoundmuffler]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.6]"
ordering = "NONE"
side = "BOTH"